import { Bracket, BracketId, Participant, SectInfo, PlayerAccount } from '../types/tournament';
import { generateTournamentBracket } from './bracketEngine';

export const DEFAULT_SECTS: Record<string, SectInfo> = {
  'Tông Môn GOD': {
    id: 'god-clan',
    name: 'Tông Môn GOD',
    description: 'Chiến đội PvP Đỉnh Cao quy tụ các bậc cao thủ thần thánh.',
    badgeColor: 'bg-amber-600/30 text-amber-300 border-amber-500/50',
    icon: '⚔️',
  },
  'Đường Môn': {
    id: 'duong-mon',
    name: 'Đường Môn',
    description: 'Tông môn đệ nhất ám khí và độc thuật, do Thần Vương Đường Tam sáng lập',
    badgeColor: 'bg-blue-600/30 text-blue-300 border-blue-500/50',
    icon: '🌀',
  },
  'Võ Hồn Điện': {
    id: 'vo-hon-dien',
    name: 'Võ Hồn Điện',
    description: 'Thế lực tối cao thống trị Đấu La Đại Lục, sở hữu vô số Phong Hào Đấu La',
    badgeColor: 'bg-amber-600/30 text-amber-300 border-amber-500/50',
    icon: '⚡',
  },
  'Sử Lai Khắc': {
    id: 'su-lai-khac',
    name: 'Sử Lai Khắc',
    description: 'Học viện quái vật danh chấn đại lục, nơi đào tạo ra Thất Quái huyền thoại',
    badgeColor: 'bg-emerald-600/30 text-emerald-300 border-emerald-500/50',
    icon: '🟢',
  },
  'Thất Bảo Lưu Ly Tông': {
    id: 'that-bao',
    name: 'Thất Bảo Lưu Ly Tông',
    description: 'Tông môn phụ trợ đệ nhất thiên hạ, giàu có và uy danh vang dội',
    badgeColor: 'bg-cyan-600/30 text-cyan-300 border-cyan-500/50',
    icon: '💎',
  },
  'Hạo Thiên Tông': {
    id: 'hao-thien',
    name: 'Hạo Thiên Tông',
    description: 'Đứng đầu Thượng Tam Tông, danh xưng thiên hạ đệ nhất lực lượng võ hồn',
    badgeColor: 'bg-red-600/30 text-red-300 border-red-500/50',
    icon: '🔨',
  },
};

export const DEFAULT_BRACKETS: Record<BracketId, Bracket> = {
  'bracket-a': {
    id: 'bracket-a',
    name: 'Bảng A (Tối Thượng > 50)',
    divisionTitle: 'Hải Thần Truyền Nhân',
    tierName: 'Tối Thượng > 50',
    theme: 'ocean',
    posterUrl: '/assets/poster_a.jpg',
    description: 'Quy tụ các bậc cường giả đỉnh cao phân khúc Tối Thượng > 50. Tranh tài tại Đảo Hải Thần với đinh ba hoàng kim rực sáng giữa sóng gầm sấm chớp.',
    primaryColor: '#06b6d4',
    accentColor: '#f59e0b',
    status: 'in_progress',
    totalRounds: 4,
  },
  'bracket-b': {
    id: 'bracket-b',
    name: 'Bảng B (Tối Thượng < 10)',
    divisionTitle: 'Sâm Lâm Bá Chủ',
    tierName: 'Tối Thượng < 10',
    theme: 'forest',
    posterUrl: '/assets/poster_b.jpg',
    description: 'Sân đấu của các chiến tướng phân khúc Tối Thượng < 10 tại Tinh Đấu Đại Sâm Lâm huyền bí dưới ánh sáng Hồn Hoàn 10 vạn năm.',
    primaryColor: '#10b981',
    accentColor: '#ef4444',
    status: 'in_progress',
    totalRounds: 4,
  },
  'bracket-c': {
    id: 'bracket-c',
    name: 'Bảng C (Rực Rỡ Trở Xuống)',
    divisionTitle: 'Sử Lai Khắc Tân Tinh',
    tierName: 'Rực Rỡ Trở Xuống',
    theme: 'village',
    posterUrl: '/assets/poster_c.jpg',
    description: 'Vũ đài nhiệt huyết dành cho 33 tuyển thủ phân khúc Rực Rỡ Trở Xuống tại Học Viện Sử Lai Khắc dưới ánh hoàng hôn rực rỡ.',
    primaryColor: '#84cc16',
    accentColor: '#f8fafc',
    status: 'in_progress',
    totalRounds: 6,
  },
};

// ==========================================
// HÌNH 1: BẢNG A (11 Thí sinh - Tối Thượng > 50)
// Thứ tự bốc thăm: LĂNGDẠ (Bye) -> Tea vs Darkness -> TTT (Bye) -> Lucky vs Parker -> TheAnh (Bye) -> Solomon vs Gấu -> QLng (Bye) -> Mèn (Bye)
// ==========================================
export const BRACKET_A_PARTICIPANTS: Participant[] = [
  {
    id: 'p-a8',
    bracketId: 'bracket-a',
    name: 'GOD乄LĂNGDẠ',
    sect: 'Tông Môn GOD',
    martialSoul: 'U Minh Linh Miêu',
    soulRank: 'Tối thượng > 50',
    soulLevel: 96,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_LANGDA&backgroundColor=9333ea',
    seedRank: 8,
    wins: 18,
    losses: 7,
    winRate: 72.0,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a6',
    bracketId: 'bracket-a',
    name: 'GOD乄Tea',
    sect: 'Tông Môn GOD',
    martialSoul: 'Lục Dực Thiên Sứ',
    soulRank: 'Tối thượng > 50',
    soulLevel: 97,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Tea&backgroundColor=059669',
    seedRank: 6,
    wins: 19,
    losses: 6,
    winRate: 76.0,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a5',
    bracketId: 'bracket-a',
    name: 'GOD乄Darkness',
    sect: 'Tông Môn GOD',
    martialSoul: 'Hắc Ám Ma Long',
    soulRank: 'Tối thượng > 50',
    soulLevel: 97,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Darkness&backgroundColor=334155',
    seedRank: 5,
    wins: 20,
    losses: 5,
    winRate: 80.0,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a1',
    bracketId: 'bracket-a',
    name: 'GOD乄TTT',
    sect: 'Tông Môn GOD',
    martialSoul: 'Hải Thần Tam Xoa Kích',
    soulRank: 'Tối thượng > 50',
    soulLevel: 99,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_TTT&backgroundColor=0284c7',
    seedRank: 1,
    wins: 25,
    losses: 2,
    winRate: 92.5,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a7',
    bracketId: 'bracket-a',
    name: 'GOD乄Lucky',
    sect: 'Tông Môn GOD',
    martialSoul: 'Thập Thủ Hỏa Phượng Hoàng',
    soulRank: 'Tối thượng > 50',
    soulLevel: 96,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Lucky&backgroundColor=ea580c',
    seedRank: 7,
    wins: 18,
    losses: 6,
    winRate: 75.0,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a10',
    bracketId: 'bracket-a',
    name: 'GOD乄Parker',
    sect: 'Tông Môn GOD',
    martialSoul: 'Lam Điện Bá Vương Long',
    soulRank: 'Tối thượng > 50',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Parker&backgroundColor=4f46e5',
    seedRank: 10,
    wins: 16,
    losses: 8,
    winRate: 66.7,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a2',
    bracketId: 'bracket-a',
    name: 'GOD乄TheAnh',
    sect: 'Tông Môn GOD',
    martialSoul: 'Tu La Ma Kiếm',
    soulRank: 'Tối thượng > 50',
    soulLevel: 99,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_TheAnh&backgroundColor=dc2626',
    seedRank: 2,
    wins: 24,
    losses: 3,
    winRate: 88.8,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a3',
    bracketId: 'bracket-a',
    name: 'GOD乄Solomon',
    sect: 'Tông Môn GOD',
    martialSoul: 'Thất Sát Kiếm',
    soulRank: 'Tối thượng > 50',
    soulLevel: 98,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Solomon&backgroundColor=7c3aed',
    seedRank: 3,
    wins: 22,
    losses: 4,
    winRate: 84.6,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a11',
    bracketId: 'bracket-a',
    name: 'GOD乄Gấu',
    sect: 'Tông Môn GOD',
    martialSoul: 'Đại Lực Kim Cương Hùng',
    soulRank: 'Tối thượng > 50',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Gau&backgroundColor=854d0e',
    seedRank: 11,
    wins: 15,
    losses: 8,
    winRate: 65.2,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a4',
    bracketId: 'bracket-a',
    name: 'GOD乄QLng',
    sect: 'Tông Môn GOD',
    martialSoul: 'Hạo Thiên Chùy',
    soulRank: 'Tối thượng > 50',
    soulLevel: 98,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_QLng&backgroundColor=d97706',
    seedRank: 4,
    wins: 21,
    losses: 5,
    winRate: 80.7,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
  {
    id: 'p-a9',
    bracketId: 'bracket-a',
    name: 'GOD乄Mèn',
    sect: 'Tông Môn GOD',
    martialSoul: 'Bạch Hổ Cuồng Nộ',
    soulRank: 'Tối thượng > 50',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Men&backgroundColor=2563eb',
    seedRank: 9,
    wins: 17,
    losses: 7,
    winRate: 70.8,
    bio: 'Đại cao thủ Bảng A - Rank Tối thượng > 50.',
  },
];

// ==========================================
// HÌNH 2: BẢNG B (11 Thí sinh - Tối Thượng < 10)
// Thứ tự bốc thăm: Giangnè (Bye) -> HULK vs Héo -> TungKa (Bye) -> GoodLuck vs Mía -> Ryuki (Bye) -> Pain vs Shadow -> Ngốc Yêu (Bye) -> Mino (Bye)
// ==========================================
export const BRACKET_B_PARTICIPANTS: Participant[] = [
  {
    id: 'p-b4',
    bracketId: 'bracket-b',
    name: 'GOD乄Giangnè',
    sect: 'Tông Môn GOD',
    martialSoul: 'Kỳ Nhung Thông Thiên Cúc',
    soulRank: 'Tối thượng < 10',
    soulLevel: 92,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Giangne&backgroundColor=eab308',
    seedRank: 4,
    wins: 17,
    losses: 5,
    winRate: 77.2,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b2',
    bracketId: 'bracket-b',
    name: 'GOD乄HULK',
    sect: 'Tông Môn GOD',
    martialSoul: 'Hoang Cổ Thần Cự Nhân',
    soulRank: 'Tối thượng < 10',
    soulLevel: 93,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_HULK&backgroundColor=16a34a',
    seedRank: 2,
    wins: 19,
    losses: 4,
    winRate: 82.6,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b1',
    bracketId: 'bracket-b',
    name: 'GOD乄Héo',
    sect: 'Tông Môn GOD',
    martialSoul: 'Bích Lân Xà Hoàng',
    soulRank: 'Tối thượng < 10',
    soulLevel: 93,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Heo&backgroundColor=059669',
    seedRank: 1,
    wins: 20,
    losses: 4,
    winRate: 83.3,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b3',
    bracketId: 'bracket-b',
    name: 'GOD乄TungKa',
    sect: 'Tông Môn GOD',
    martialSoul: 'Cốt Long Không Gian',
    soulRank: 'Tối thượng < 10',
    soulLevel: 92,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_TungKa&backgroundColor=64748b',
    seedRank: 3,
    wins: 18,
    losses: 5,
    winRate: 78.2,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b8',
    bracketId: 'bracket-b',
    name: 'GOD乄GoodLuck',
    sect: 'Tông Môn GOD',
    martialSoul: 'Hắc Ám Ma Hổ',
    soulRank: 'Tối thượng < 10',
    soulLevel: 90,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_GoodLuck&backgroundColor=1e293b',
    seedRank: 8,
    wins: 15,
    losses: 7,
    winRate: 68.2,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b9',
    bracketId: 'bracket-b',
    name: 'GOD乄Mía',
    sect: 'Tông Môn GOD',
    martialSoul: 'Cửu Bảo Lưu Ly Tháp',
    soulRank: 'Tối thượng < 10',
    soulLevel: 90,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Mia&backgroundColor=0284c7',
    seedRank: 9,
    wins: 14,
    losses: 7,
    winRate: 66.7,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b5',
    bracketId: 'bracket-b',
    name: 'GOD乄Ryuki',
    sect: 'Tông Môn GOD',
    martialSoul: 'Quỷ Mị Huyễn Ảnh',
    soulRank: 'Tối thượng < 10',
    soulLevel: 91,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Ryuki&backgroundColor=475569',
    seedRank: 5,
    wins: 16,
    losses: 6,
    winRate: 72.7,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b6',
    bracketId: 'bracket-b',
    name: 'GOD乄Pain',
    sect: 'Tông Môn GOD',
    martialSoul: 'Độc Giác Hỏa Phượng',
    soulRank: 'Tối thượng < 10',
    soulLevel: 91,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Pain&backgroundColor=ef4444',
    seedRank: 6,
    wins: 16,
    losses: 6,
    winRate: 72.7,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b11',
    bracketId: 'bracket-b',
    name: 'GOD乄Shadow',
    sect: 'Tông Môn GOD',
    martialSoul: 'Ám Ảnh Ma Lang',
    soulRank: 'Tối thượng < 10',
    soulLevel: 89,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Shadow&backgroundColor=0f172a',
    seedRank: 11,
    wins: 13,
    losses: 8,
    winRate: 61.9,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b7',
    bracketId: 'bracket-b',
    name: 'GOD乄Ngốc Yêu',
    sect: 'Tông Môn GOD',
    martialSoul: 'Băng Tinh Phượng Hoàng',
    soulRank: 'Tối thượng < 10',
    soulLevel: 90,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_NgocYeu&backgroundColor=06b6d4',
    seedRank: 7,
    wins: 15,
    losses: 6,
    winRate: 71.4,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
  {
    id: 'p-b10',
    bracketId: 'bracket-b',
    name: 'GOD乄Mino',
    sect: 'Tông Môn GOD',
    martialSoul: 'Tà Ma Bạch Hổ',
    soulRank: 'Tối thượng < 10',
    soulLevel: 89,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Mino&backgroundColor=6366f1',
    seedRank: 10,
    wins: 14,
    losses: 8,
    winRate: 63.6,
    bio: 'Chiến tướng Bảng B - Rank Tối thượng < 10.',
  },
];

// ==========================================
// HÌNH 3 & 4: BẢNG C (33 Thí sinh - Rực Rỡ Trở Xuống)
// ==========================================
export const BRACKET_C_PARTICIPANTS: Participant[] = [
  { id: 'p-c4', bracketId: 'bracket-c', name: 'GOD乄Hạo ca', sect: 'Tông Môn GOD', martialSoul: 'Hạo Thiên Chùy', soulRank: 'Rực rỡ trở xuống', soulLevel: 84, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_HaoCa&backgroundColor=ea580c', seedRank: 4, wins: 14, losses: 7, winRate: 66.7, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c33', bracketId: 'bracket-c', name: 'GOD乄Gin', sect: 'Tông Môn GOD', martialSoul: 'Ngân Lôi Thương', soulRank: 'Rực rỡ trở xuống', soulLevel: 70, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Gin&backgroundColor=3b82f6', seedRank: 33, wins: 2, losses: 14, winRate: 12.5, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c8', bracketId: 'bracket-c', name: 'GOD乄xYunol', sect: 'Tông Môn GOD', martialSoul: 'Băng Hỏa Lưỡng Nghi Thương', soulRank: 'Rực rỡ trở xuống', soulLevel: 82, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_xYunol&backgroundColor=0284c7', seedRank: 8, wins: 12, losses: 8, winRate: 60.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c9', bracketId: 'bracket-c', name: 'GOD乄ĐẾ', sect: 'Tông Môn GOD', martialSoul: 'Đế Hoàng Thụy Thú', soulRank: 'Rực rỡ trở xuống', soulLevel: 81, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_De&backgroundColor=eab308', seedRank: 9, wins: 11, losses: 8, winRate: 57.9, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c6', bracketId: 'bracket-c', name: 'GOD乄Huy12', sect: 'Tông Môn GOD', martialSoul: 'Liệt Diệm Cuồng Sư', soulRank: 'Rực rỡ trở xuống', soulLevel: 83, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Huy12&backgroundColor=dc2626', seedRank: 6, wins: 13, losses: 8, winRate: 61.9, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c31', bracketId: 'bracket-c', name: 'GOD乄Hades', sect: 'Tông Môn GOD', martialSoul: 'Minh Vương Kiếm', soulRank: 'Rực rỡ trở xuống', soulLevel: 70, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Hades&backgroundColor=172554', seedRank: 31, wins: 3, losses: 13, winRate: 18.8, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c20', bracketId: 'bracket-c', name: 'GOD乄Namaka06', sect: 'Tông Môn GOD', martialSoul: 'Thanh Điểu', soulRank: 'Rực rỡ trở xuống', soulLevel: 76, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Namaka06&backgroundColor=0284c7', seedRank: 20, wins: 7, losses: 10, winRate: 41.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c17', bracketId: 'bracket-c', name: 'GOD乄gà con', sect: 'Tông Môn GOD', martialSoul: 'Thúy Điểu', soulRank: 'Rực rỡ trở xuống', soulLevel: 77, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_GaCon&backgroundColor=15803d', seedRank: 17, wins: 8, losses: 9, winRate: 47.1, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c2', bracketId: 'bracket-c', name: 'GOD乄TiểuLy', sect: 'Tông Môn GOD', martialSoul: 'Cửu Tâm Hải Đường', soulRank: 'Rực rỡ trở xuống', soulLevel: 85, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_TieuLy&backgroundColor=ec4899', seedRank: 2, wins: 15, losses: 6, winRate: 71.4, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c29', bracketId: 'bracket-c', name: 'GOD乄JetJet', sect: 'Tông Môn GOD', martialSoul: 'Phong Thần Dực', soulRank: 'Rực rỡ trở xuống', soulLevel: 71, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_JetJet&backgroundColor=0369a1', seedRank: 29, wins: 3, losses: 12, winRate: 20.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c21', bracketId: 'bracket-c', name: 'GOD乄Daim', sect: 'Tông Môn GOD', martialSoul: 'Băng Phượng Hoàng', soulRank: 'Rực rỡ trở xuống', soulLevel: 75, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Daim&backgroundColor=06b6d4', seedRank: 21, wins: 6, losses: 10, winRate: 37.5, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c27', bracketId: 'bracket-c', name: 'GOD乄Đời nó bạc', sect: 'Tông Môn GOD', martialSoul: 'Tật Phong Ma Lang', soulRank: 'Rực rỡ trở xuống', soulLevel: 72, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_DoiNoBac&backgroundColor=1e293b', seedRank: 27, wins: 4, losses: 12, winRate: 25.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c15', bracketId: 'bracket-c', name: 'GOD乄unreal', sect: 'Tông Môn GOD', martialSoul: 'Huyễn Thần Điệp', soulRank: 'Rực rỡ trở xuống', soulLevel: 78, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_unreal&backgroundColor=8b5cf6', seedRank: 15, wins: 9, losses: 9, winRate: 50.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c18', bracketId: 'bracket-c', name: 'GOD乄VYX', sect: 'Tông Môn GOD', martialSoul: 'Hắc Diễm Phượng', soulRank: 'Rực rỡ trở xuống', soulLevel: 77, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_VYX&backgroundColor=b91c1c', seedRank: 18, wins: 8, losses: 10, winRate: 44.4, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c1', bracketId: 'bracket-c', name: 'GOD乄NCDEC', sect: 'Tông Môn GOD', martialSoul: 'Hải Thần Tam Xoa Kích', soulRank: 'Rực rỡ trở xuống', soulLevel: 85, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_NCDEC&backgroundColor=0284c7', seedRank: 1, wins: 16, losses: 5, winRate: 76.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c24', bracketId: 'bracket-c', name: 'GOD乄longca', sect: 'Tông Môn GOD', martialSoul: 'Viêm Long Thương', soulRank: 'Rực rỡ trở xuống', soulLevel: 74, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_longca&backgroundColor=b91c1c', seedRank: 24, wins: 5, losses: 11, winRate: 31.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c32', bracketId: 'bracket-c', name: 'GOD乄TiểuLy 2', sect: 'Tông Môn GOD', martialSoul: 'Tuyết Hồ', soulRank: 'Rực rỡ trở xuống', soulLevel: 70, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_TieuLy2&backgroundColor=0891b2', seedRank: 32, wins: 2, losses: 13, winRate: 13.3, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c16', bracketId: 'bracket-c', name: 'GOD乄sailầm', sect: 'Tông Môn GOD', martialSoul: 'Bá Vương Thương', soulRank: 'Rực rỡ trở xuống', soulLevel: 78, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_sai_lam&backgroundColor=475569', seedRank: 16, wins: 9, losses: 9, winRate: 50.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  
  // Screenshot 2: ILoveU (Bye) -> Diệm vs Tà
  { id: 'p-c5', bracketId: 'bracket-c', name: 'GOD乄ILoveU', sect: 'Tông Môn GOD', martialSoul: 'U Minh Linh Miêu', soulRank: 'Rực rỡ trở xuống', soulLevel: 83, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_ILoveU&backgroundColor=9333ea', seedRank: 5, wins: 13, losses: 7, winRate: 65.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c26', bracketId: 'bracket-c', name: 'GOD乄Diệm', sect: 'Tông Môn GOD', martialSoul: 'Liệt Diệm Thần Trượng', soulRank: 'Rực rỡ trở xuống', soulLevel: 73, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Diem&backgroundColor=c2410c', seedRank: 26, wins: 4, losses: 11, winRate: 26.7, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c14', bracketId: 'bracket-c', name: 'GOD乄Tà', sect: 'Tông Môn GOD', martialSoul: 'Tà Thần Câu', soulRank: 'Rực rỡ trở xuống', soulLevel: 79, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Ta&backgroundColor=581c87', seedRank: 14, wins: 10, losses: 9, winRate: 52.6, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },

  { id: 'p-c13', bracketId: 'bracket-c', name: 'GOD乄kiemlai', sect: 'Tông Môn GOD', martialSoul: 'Thất Sát Kiếm', soulRank: 'Rực rỡ trở xuống', soulLevel: 79, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_kiemlai&backgroundColor=7c3aed', seedRank: 13, wins: 10, losses: 9, winRate: 52.6, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c7', bracketId: 'bracket-c', name: 'GOD乄Hung', sect: 'Tông Môn GOD', martialSoul: 'Đại Lực Thần Ma', soulRank: 'Rực rỡ trở xuống', soulLevel: 82, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Hung&backgroundColor=ca8a04', seedRank: 7, wins: 12, losses: 7, winRate: 63.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c30', bracketId: 'bracket-c', name: 'GOD乄MaHoàng', sect: 'Tông Môn GOD', martialSoul: 'Ma Hoàng Đế Trượng', soulRank: 'Rực rỡ trở xuống', soulLevel: 71, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_MaHoang&backgroundColor=581c87', seedRank: 30, wins: 3, losses: 12, winRate: 20.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c3', bracketId: 'bracket-c', name: 'GOD乄Panther', sect: 'Tông Môn GOD', martialSoul: 'Hắc Ám Báo Vương', soulRank: 'Rực rỡ trở xuống', soulLevel: 84, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Panther&backgroundColor=18181b', seedRank: 3, wins: 15, losses: 7, winRate: 68.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c10', bracketId: 'bracket-c', name: 'GOD乄βαβγ', sect: 'Tông Môn GOD', martialSoul: 'Thánh Quang Hổ', soulRank: 'Rực rỡ trở xuống', soulLevel: 81, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_baby&backgroundColor=f59e0b', seedRank: 10, wins: 11, losses: 8, winRate: 57.9, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c11', bracketId: 'bracket-c', name: 'GOD乄Chuột', sect: 'Tông Môn GOD', martialSoul: 'Tầm Bảo Thử', soulRank: 'Rực rỡ trở xuống', soulLevel: 80, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Chuot&backgroundColor=78716c', seedRank: 11, wins: 11, losses: 9, winRate: 55.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c12', bracketId: 'bracket-c', name: 'GOD乄YuLyn', sect: 'Tông Môn GOD', martialSoul: 'Băng Tinh Phượng Hoàng', soulRank: 'Rực rỡ trở xuống', soulLevel: 80, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_YuLyn&backgroundColor=06b6d4', seedRank: 12, wins: 10, losses: 9, winRate: 52.6, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c19', bracketId: 'bracket-c', name: 'GOD乄Vũ Lân', sect: 'Tông Môn GOD', martialSoul: 'Kim Long Vương', soulRank: 'Rực rỡ trở xuống', soulLevel: 76, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_VuLan&backgroundColor=ca8a04', seedRank: 19, wins: 7, losses: 10, winRate: 41.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c22', bracketId: 'bracket-c', name: 'GOD乄ThatGird', sect: 'Tông Môn GOD', martialSoul: 'Cửu Bảo Lưu Ly Tháp', soulRank: 'Rực rỡ trở xuống', soulLevel: 75, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_ThatGird&backgroundColor=0891b2', seedRank: 22, wins: 6, losses: 10, winRate: 37.5, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c23', bracketId: 'bracket-c', name: 'GOD乄Tít', sect: 'Tông Môn GOD', martialSoul: 'Lam Điện Bá Vương Long', soulRank: 'Rực rỡ trở xuống', soulLevel: 74, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Tit&backgroundColor=4f46e5', seedRank: 23, wins: 6, losses: 11, winRate: 35.3, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c25', bracketId: 'bracket-c', name: 'GOD乄Huynh', sect: 'Tông Môn GOD', martialSoul: 'Thiên Cương Thuẫn', soulRank: 'Rực rỡ trở xuống', soulLevel: 73, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_Huynh&backgroundColor=374151', seedRank: 25, wins: 5, losses: 11, winRate: 31.2, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c28', bracketId: 'bracket-c', name: 'GOD乄DEATH', sect: 'Tông Môn GOD', martialSoul: 'Tử Thần Liêm Đao', soulRank: 'Rực rỡ trở xuống', soulLevel: 72, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_DEATH&backgroundColor=0f172a', seedRank: 28, wins: 4, losses: 12, winRate: 25.0, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
  { id: 'p-c34', bracketId: 'bracket-c', name: 'GOD乄DarkGirl', sect: 'Đường Môn', martialSoul: 'Chu hoàng', soulRank: 'Rực rỡ trở xuống', soulLevel: 90, avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=GOD_DarkGirl&backgroundColor=9333ea', seedRank: 34, wins: 10, losses: 6, winRate: 62.5, bio: 'Tuyển thủ Bảng C - Rank Rực rỡ trở xuống.' },
];

export const INITIAL_PLAYER_ACCOUNTS: Record<string, PlayerAccount> = {
  "ta": {
    "playerName": "GOD乄Tà",
    "username": "ta",
    "password": "tadocco",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "dongtam9555@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 15:16:25 +0000"
  },
  "solomon": {
    "playerName": "GOD乄Solomon",
    "username": "solomon",
    "password": "solomonkiemtien",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "minhtrian0706@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 14:17:28 +0000"
  },
  "vulan": {
    "playerName": "GOD乄Vũ Lân",
    "username": "vulan",
    "password": "vulanmahoang",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "Quatlam2024@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:56:12 +0000"
  },
  "gau": {
    "playerName": "GOD乄Gấu",
    "username": "gau",
    "password": "gaudocco",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "Sygau1995@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:47:37 +0000"
  },
  "hades": {
    "playerName": "GOD乄Hades",
    "username": "hades",
    "password": "hadestop1",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "luulinhfacebookads@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:45:22 +0000"
  },
  "tit": {
    "playerName": "GOD乄Tít",
    "username": "tit",
    "password": "tittuthandao",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "ducthuan2002nd@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:37:38 +0000"
  },
  "tea": {
    "playerName": "GOD乄Tea",
    "username": "tea",
    "password": "teadeptrai",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "test.tea@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 11:14:03 +0000"
  },
  "huynh": {
    "playerName": "GOD乄Huynh",
    "username": "huynh",
    "password": "huynhbachthieu",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "huynhvipboy5@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:35:19 +0000"
  },
  "mahoang": {
    "playerName": "GOD乄MaHoàng",
    "username": "mahoang",
    "password": "mahoangbachthieu",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "wlink1611@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:31:51 +0000"
  },
  "giangne": {
    "playerName": "GOD乄Giangnè",
    "username": "giangne",
    "password": "giangnetop2",
    "bracketName": "Bảng B (Tối Thượng < 10)",
    "email": "gh5766420@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:31:27 +0000"
  },
  "heo": {
    "playerName": "GOD乄Héo",
    "username": "heo",
    "password": "heothanma",
    "bracketName": "Bảng B (Tối Thượng < 10)",
    "email": "dotronghieu140620053@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:28:01 +0000"
  },
  "men": {
    "playerName": "GOD乄Mèn",
    "username": "men",
    "password": "mentranhba",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "phuctkdpro@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:23:10 +0000"
  },
  "qlng": {
    "playerName": "GOD乄QLng",
    "username": "qlng",
    "password": "qlngkiemtien",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "minhhuy7001@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:21:28 +0000"
  },
  "goodluck": {
    "playerName": "GOD乄GoodLuck",
    "username": "goodluck",
    "password": "goodlucktuyettrieu",
    "bracketName": "Bảng B (Tối Thượng < 10)",
    "email": "bqhuy0846446@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:20:37 +0000"
  },
  "yulyn": {
    "playerName": "GOD乄YuLyn",
    "username": "yulyn",
    "password": "yulynbatbai",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "yulyn2205@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:20:17 +0000"
  },
  "hung": {
    "playerName": "GOD乄Hung",
    "username": "hung",
    "password": "hungchiensi",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "iamhung1706@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:18:40 +0000"
  },
  "lucky": {
    "playerName": "GOD乄Lucky",
    "username": "lucky",
    "password": "luckysieucap",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "hoanghai2909@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:17:03 +0000"
  },
  "ttt": {
    "playerName": "GOD乄TTT",
    "username": "ttt",
    "password": "tttlongthan",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "thaithien010104@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:14:38 +0000"
  },
  "hulk": {
    "playerName": "GOD乄HULK",
    "username": "hulk",
    "password": "hulkdeptrai",
    "bracketName": "Bảng B (Tối Thượng < 10)",
    "email": "voquocthang18092005@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 11:40:18 +0000"
  },
  "jetjet": {
    "playerName": "GOD乄JetJet",
    "username": "jetjet",
    "password": "jetjetquangthan",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "boycunli@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:12:36 +0000"
  },
  "god": {
    "playerName": "GOD乄ĐẾ",
    "username": "god",
    "password": "godhonsu99",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "kientq888@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:11:25 +0000"
  },
  "daim": {
    "playerName": "GOD乄Daim",
    "username": "daim",
    "password": "daimvotri",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "hoanglong.147@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:10:33 +0000"
  },
  "diem": {
    "playerName": "GOD乄Diệm",
    "username": "diem",
    "password": "diemdeptrai",
    "bracketName": "Bảng C (Rực Rỡ Trở Xuống)",
    "email": "tantai.21082005@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:08:41 +0000"
  },
  "darkness": {
    "playerName": "GOD乄Darkness",
    "username": "darkness",
    "password": "darknessbachthieu",
    "bracketName": "Bảng A (Tối Thượng > 50)",
    "email": "tranminhhieu11a3ntt@gmail.com",
    "claimedAt": "Mon, 17 Aug 2026 13:08:09 +0000"
  }
};

export function getInitialTournamentData() {
  const participantsMap: Record<string, Participant> = {};
  [...BRACKET_A_PARTICIPANTS, ...BRACKET_B_PARTICIPANTS, ...BRACKET_C_PARTICIPANTS].forEach((p) => {
    participantsMap[p.id] = p;
  });

  const matchesMap: Record<string, any> = {
    ...generateTournamentBracket('bracket-a', BRACKET_A_PARTICIPANTS, false),
    ...generateTournamentBracket('bracket-b', BRACKET_B_PARTICIPANTS, false),
    ...generateTournamentBracket('bracket-c', BRACKET_C_PARTICIPANTS, false),
  };

  return {
    brackets: DEFAULT_BRACKETS,
    participants: participantsMap,
    matches: matchesMap,
    playerAccounts: { ...INITIAL_PLAYER_ACCOUNTS },
  };
}
