import { Bracket, BracketId, Participant, SectInfo } from '../types/tournament';
import { generateTournamentBracket } from './bracketEngine';

export const DEFAULT_SECTS: Record<string, SectInfo> = {
  'Đường Môn': {
    id: 'duong-mon',
    name: 'Đường Môn',
    description: 'Tông môn đệ nhất ám khí và độc thuật, do Thần Vương Đường Tam sáng lập',
    badgeColor: 'bg-blue-600/30 text-blue-300 border-blue-500/50',
    icon: '🌀',
  },
  'Võ Hồn Điện': {
    id: 'vo-hon-dien',
    name: 'Võ Hồn Điện',
    description: 'Thế lực tối cao thống trị Đấu La Đại Lục, sở hữu vô số Phong Hào Đấu La',
    badgeColor: 'bg-amber-600/30 text-amber-300 border-amber-500/50',
    icon: '⚡',
  },
  'Sử Lai Khắc': {
    id: 'su-lai-khac',
    name: 'Sử Lai Khắc',
    description: 'Học viện quái vật danh chấn đại lục, nơi đào tạo ra Thất Quái huyền thoại',
    badgeColor: 'bg-emerald-600/30 text-emerald-300 border-emerald-500/50',
    icon: '🟢',
  },
  'Thất Bảo Lưu Ly Tông': {
    id: 'that-bao',
    name: 'Thất Bảo Lưu Ly Tông',
    description: 'Tông môn phụ trợ đệ nhất thiên hạ, giàu có và uy danh vang dội',
    badgeColor: 'bg-cyan-600/30 text-cyan-300 border-cyan-500/50',
    icon: '💎',
  },
  'Hạo Thiên Tông': {
    id: 'hao-thien',
    name: 'Hạo Thiên Tông',
    description: 'Đứng đầu Thượng Tam Tông, danh xưng thiên hạ đệ nhất lực lượng võ hồn',
    badgeColor: 'bg-red-600/30 text-red-300 border-red-500/50',
    icon: '🔨',
  },
  'Lam Điện Tông': {
    id: 'lam-dien',
    name: 'Lam Điện Bá Vương Long',
    description: 'Thượng Tam Tông đệ nhất thú võ hồn công kích cường đại',
    badgeColor: 'bg-indigo-600/30 text-indigo-300 border-indigo-500/50',
    icon: '🐉',
  },
  'Thánh Hồn Thôn': {
    id: 'thanh-hon',
    name: 'Thánh Hồn Thôn',
    description: 'Ngôi làng mộc mạc nơi Hải Thần Đường Tam bắt đầu thức tỉnh Hồn Lực',
    badgeColor: 'bg-lime-600/30 text-lime-300 border-lime-500/50',
    icon: '🌾',
  },
};

export const DEFAULT_BRACKETS: Record<BracketId, Bracket> = {
  'bracket-a': {
    id: 'bracket-a',
    name: 'Bảng A (Hạng Chuyên Nghiệp)',
    divisionTitle: 'Hải Thần Truyền Nhân',
    tierName: 'Đỉnh Cấp Thần Vương',
    theme: 'ocean',
    posterUrl: '/assets/poster_a.jpg',
    description: 'Quy tụ các bậc cường giả đỉnh cao của Đấu La Đại Lục. Tranh tài tại Đảo Hải Thần với đinh ba hoàng kim rực sáng giữa sóng gầm sấm chớp.',
    primaryColor: '#06b6d4',
    accentColor: '#f59e0b',
    status: 'in_progress',
    totalRounds: 4,
  },
  'bracket-b': {
    id: 'bracket-b',
    name: 'Bảng B (Hạng Bán Chuyên)',
    divisionTitle: 'Sâm Lâm Bá Chủ',
    tierName: 'Phong Hào Cường Giả',
    theme: 'forest',
    posterUrl: '/assets/poster_b.jpg',
    description: 'Sân đấu của các trưởng lão và chiến tướng dạn dày sương gió tại Tinh Đấu Đại Sâm Lâm huyền bí dưới ánh sáng Hồn Hoàn 10 vạn năm.',
    primaryColor: '#10b981',
    accentColor: '#ef4444',
    status: 'in_progress',
    totalRounds: 3,
  },
  'bracket-c': {
    id: 'bracket-c',
    name: 'Bảng C (Hạng Phong Trào)',
    divisionTitle: 'Sử Lai Khắc Tân Tinh',
    tierName: 'Khởi Nguyên Hồn Sư',
    theme: 'village',
    posterUrl: '/assets/poster_c.jpg',
    description: 'Vũ đài nhiệt huyết dành cho các tân binh và hậu duệ trẻ tại Thánh Hồn Thôn dưới ánh bình minh rực rỡ, nuôi dưỡng khát vọng vươn lên thành Thần.',
    primaryColor: '#84cc16',
    accentColor: '#f8fafc',
    status: 'in_progress',
    totalRounds: 3,
  },
};

// Preset Participants for Bảng A (13 players - demonstrates 3 Byes and 3rd place match!)
export const BRACKET_A_PARTICIPANTS: Participant[] = [
  {
    id: 'p-a1',
    bracketId: 'bracket-a',
    name: 'Đường Tam',
    sect: 'Đường Môn',
    martialSoul: 'Lam Ngân Hoàng & Hạo Thiên Chùy',
    soulRank: 'Cấp 99 (Hải Thần / Tu La Thần)',
    soulLevel: 99,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=tangsan&backgroundColor=0284c7',
    seedRank: 1,
    wins: 28,
    losses: 1,
    winRate: 96.5,
    bio: 'Truyền nhân Hải Thần, lãnh tụ Sử Lai Khắc Thất Quái, tinh thông Đường Môn Tuyệt Học.',
  },
  {
    id: 'p-a2',
    bracketId: 'bracket-a',
    name: 'Thiên Nhận Tuyết',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Lục Dực Thiên Sứ',
    soulRank: 'Cấp 99 (Thiên Sứ Thần)',
    soulLevel: 99,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=qianrenxue&backgroundColor=f59e0b',
    seedRank: 2,
    wins: 26,
    losses: 2,
    winRate: 92.8,
    bio: 'Thần cấp Lục Dực Thiên Sứ, nắm giữ thần thánh quang huy và kiếm khí vô song.',
  },
  {
    id: 'p-a3',
    bracketId: 'bracket-a',
    name: 'Đới Mộc Bạch',
    sect: 'Sử Lai Khắc',
    martialSoul: 'Tà Mâu Bạch Hổ',
    soulRank: 'Cấp 95 (Bạch Hổ Đấu La)',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=mubai&backgroundColor=eab308',
    seedRank: 3,
    wins: 22,
    losses: 4,
    winRate: 84.6,
    bio: 'Đại ca Thất Quái, sức mạnh cuồng bạo xé toạc chiến trường với U Minh Bạch Hổ.',
  },
  {
    id: 'p-a4',
    bracketId: 'bracket-a',
    name: 'Hồ Liệt Na',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Yêu Hồ Hoàng Kim',
    soulRank: 'Cấp 93 (Yêu Hồ Đấu La)',
    soulLevel: 93,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=huoliena&backgroundColor=ec4899',
    seedRank: 4,
    wins: 20,
    losses: 5,
    winRate: 80.0,
    bio: 'Thánh Nữ Võ Hồn Điện, tuyệt đỉnh mị thuật làm mê hoặc mọi giác quan đối thủ.',
  },
  {
    id: 'p-a5',
    bracketId: 'bracket-a',
    name: 'Chu Trúc Thanh',
    sect: 'Sử Lai Khắc',
    martialSoul: 'U Minh Linh Miêu',
    soulRank: 'Cấp 94 (U Minh Đấu La)',
    soulLevel: 94,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=zhucing&backgroundColor=6366f1',
    seedRank: 5,
    wins: 21,
    losses: 4,
    winRate: 84.0,
    bio: 'Tốc độ cực hạn, thích khách bóng đêm với những đòn tấn công chí mạng.',
  },
  {
    id: 'p-a6',
    bracketId: 'bracket-a',
    name: 'Tà Nguyệt',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Nguyệt Nhận',
    soulRank: 'Cấp 93 (Nguyệt Nhận Đấu La)',
    soulLevel: 93,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=xieyue&backgroundColor=8b5cf6',
    seedRank: 6,
    wins: 19,
    losses: 6,
    winRate: 76.0,
    bio: 'Đội trưởng Hoàng Kim Đời Sau, phong cách chiến đấu sắc bén và quyết đoán.',
  },
  {
    id: 'p-a7',
    bracketId: 'bracket-a',
    name: 'Mã Hồng Tuấn',
    sect: 'Sử Lai Khắc',
    martialSoul: 'Cửu Thao Phượng Hoàng',
    soulRank: 'Cấp 94 (Phượng Hoàng Đấu La)',
    soulLevel: 94,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=hongjun&backgroundColor=f97316',
    seedRank: 7,
    wins: 19,
    losses: 6,
    winRate: 76.0,
    bio: 'Hỏa diễm tột cùng thiêu rụi vạn vật, nắm giữ bất tử phượng hoàng hỏa.',
  },
  {
    id: 'p-a8',
    bracketId: 'bracket-a',
    name: 'Diễm',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Hỏa Diễm Lĩnh Chủ',
    soulRank: 'Cấp 92 (Hỏa Diễm Đấu La)',
    soulLevel: 92,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=yan&backgroundColor=dc2626',
    seedRank: 8,
    wins: 17,
    losses: 7,
    winRate: 70.8,
    bio: 'Lực lượng nham thạch và ngọn lửa cuồng nộ phòng ngự phản kích.',
  },
  {
    id: 'p-a9',
    bracketId: 'bracket-a',
    name: 'Ninh Vinh Vinh',
    sect: 'Thất Bảo Lưu Ly Tông',
    martialSoul: 'Cửu Bảo Lưu Ly Tháp',
    soulRank: 'Cấp 94 (Cửu Thải Đấu La)',
    soulLevel: 94,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=rongrong&backgroundColor=06b6d4',
    seedRank: 9,
    wins: 18,
    losses: 6,
    winRate: 75.0,
    bio: 'Thiên hạ đệ nhất phụ trợ, gia tăng toàn diện sức mạnh và sinh mệnh thần quang.',
  },
  {
    id: 'p-a10',
    bracketId: 'bracket-a',
    name: 'Áo Tư Tạp',
    sect: 'Sử Lai Khắc',
    martialSoul: 'Bát Bảo Đại Tràng',
    soulRank: 'Cấp 94 (Thực Thần Đấu La)',
    soulLevel: 94,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=oscar&backgroundColor=10b981',
    seedRank: 10,
    wins: 18,
    losses: 6,
    winRate: 75.0,
    bio: 'Thực vật hệ Hồn Sư kỳ tích, sở hữu Hồn Kỹ sao chép năng lực chiến đấu võ hồn khác.',
  },
  {
    id: 'p-a11',
    bracketId: 'bracket-a',
    name: 'Ngọc Thiên Hằng',
    sect: 'Lam Điện Tông',
    martialSoul: 'Lam Điện Bá Vương Long',
    soulRank: 'Cấp 91 (Bá Vương Đấu La)',
    soulLevel: 91,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=tianheng&backgroundColor=3b82f6',
    seedRank: 11,
    wins: 16,
    losses: 8,
    winRate: 66.7,
    bio: 'Lôi điện long hóa chi uy, chấn áp đối thủ bằng lôi đình sấm sét liên hoàn.',
  },
  {
    id: 'p-a12',
    bracketId: 'bracket-a',
    name: 'Độc Cô Nhạn',
    sect: 'Hoàng Đấu',
    martialSoul: 'Bích Lân Xà Hoàng',
    soulRank: 'Cấp 90 (Bích Lân Đấu La)',
    soulLevel: 90,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=duguyan&backgroundColor=14b8a6',
    seedRank: 12,
    wins: 15,
    losses: 9,
    winRate: 62.5,
    bio: 'Độc khí lan tràn khuynh đảo trận địa, khống chế toàn cục với kịch độc.',
  },
  {
    id: 'p-a13',
    bracketId: 'bracket-a',
    name: 'Thủy Băng Nhi',
    sect: 'Thiên Thủy',
    martialSoul: 'Băng Phượng Hoàng',
    soulRank: 'Cấp 90 (Băng Hoàng Đấu La)',
    soulLevel: 90,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=bingEr&backgroundColor=38bdf8',
    seedRank: 13,
    wins: 15,
    losses: 8,
    winRate: 65.2,
    bio: 'Băng phong lãnh vực, đóng băng đối thủ tức khắc trong tuyết sương tuyệt đối.',
  },
];

// Preset Participants for Bảng B (8 players)
export const BRACKET_B_PARTICIPANTS: Participant[] = [
  {
    id: 'p-b1',
    bracketId: 'bracket-b',
    name: 'Đường Hạo',
    sect: 'Hạo Thiên Tông',
    martialSoul: 'Hạo Thiên Chùy',
    soulRank: 'Cấp 97 (Hạo Thiên Đấu La)',
    soulLevel: 97,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=tanghao&backgroundColor=b91c1c',
    seedRank: 1,
    wins: 35,
    losses: 2,
    winRate: 94.5,
    bio: 'Đại Tu Di Chùy phá tan vạn cổ, từng một chùy đả thương 3 đại Phong Hào Đấu La Võ Hồn Điện.',
  },
  {
    id: 'p-b2',
    bracketId: 'bracket-b',
    name: 'Trần Tâm',
    sect: 'Thất Bảo Lưu Ly Tông',
    martialSoul: 'Thất Sát Kiếm',
    soulRank: 'Cấp 97 (Kiếm Đấu La)',
    soulLevel: 97,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=chenxin&backgroundColor=3b82f6',
    seedRank: 2,
    wins: 32,
    losses: 3,
    winRate: 91.4,
    bio: 'Thiên hạ đệ nhất công kích kiếm tu, kiếm ý thông thiên triệt địa.',
  },
  {
    id: 'p-b3',
    bracketId: 'bracket-b',
    name: 'Cổ Dung',
    sect: 'Thất Bảo Lưu Ly Tông',
    martialSoul: 'Cốt Long Không Gian',
    soulRank: 'Cấp 95 (Cốt Đấu La)',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=gurong&backgroundColor=64748b',
    seedRank: 3,
    wins: 28,
    losses: 5,
    winRate: 84.8,
    bio: 'Đệ nhất phòng ngự và thao túng không gian dị biến khôn lường.',
  },
  {
    id: 'p-b4',
    bracketId: 'bracket-b',
    name: 'Độc Cô Bác',
    sect: 'Đường Môn',
    martialSoul: 'Bích Lân Xà Hoàng',
    soulRank: 'Cấp 92 (Độc Đấu La)',
    soulLevel: 92,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=dugubo&backgroundColor=059669',
    seedRank: 4,
    wins: 25,
    losses: 7,
    winRate: 78.1,
    bio: 'Bậc thầy dụng độc, một trận kịch độc có thể tàn sát cả một quân đoàn.',
  },
  {
    id: 'p-b5',
    bracketId: 'bracket-b',
    name: 'Nguyệt Quan',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Kỳ Nhung Thông Thiên Cúc',
    soulRank: 'Cấp 95 (Cúc Đấu La)',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=yueguan&backgroundColor=eab308',
    seedRank: 5,
    wins: 24,
    losses: 8,
    winRate: 75.0,
    bio: 'Hoa cỏ tiên phẩm uy năng kinh người, kết hợp cùng Quỷ Mị tạo Lưỡng Cực Tĩnh Chỉ Lĩnh Vực.',
  },
  {
    id: 'p-b6',
    bracketId: 'bracket-b',
    name: 'Quỷ Mị',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Quỷ Ảnh Vô Hình',
    soulRank: 'Cấp 95 (Quỷ Đấu La)',
    soulLevel: 95,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=guimei&backgroundColor=334155',
    seedRank: 6,
    wins: 23,
    losses: 8,
    winRate: 74.2,
    bio: 'Thân ảnh như u linh bất diệt, miễn nhiễm hầu hết đòn công kích vật lý.',
  },
  {
    id: 'p-b7',
    bracketId: 'bracket-b',
    name: 'Dương Vô Địch',
    sect: 'Đường Môn (Phá Đường)',
    martialSoul: 'Phá Hồn Thương',
    soulRank: 'Cấp 89 (Hồn Đấu La)',
    soulLevel: 89,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=wudi&backgroundColor=991b1b',
    seedRank: 7,
    wins: 22,
    losses: 9,
    winRate: 71.0,
    bio: 'Chuyên tâm vào cực hạn công kích, cây thương đâm ra không bao giờ lùi bước.',
  },
  {
    id: 'p-b8',
    bracketId: 'bracket-b',
    name: 'Triệu Vô Cực',
    sect: 'Sử Lai Khắc',
    martialSoul: 'Đại Lực Kim Cương Hùng',
    soulRank: 'Cấp 82 (Hồn Đấu La)',
    soulLevel: 82,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=zhaowuji&backgroundColor=ca8a04',
    seedRank: 8,
    wins: 20,
    losses: 10,
    winRate: 66.7,
    bio: 'Bất Động Minh Vương lừng danh giang hồ với thể phách mình đồng da sắt.',
  },
];

// Preset Participants for Bảng C (6 players - demonstrates 2 Byes!)
export const BRACKET_C_PARTICIPANTS: Participant[] = [
  {
    id: 'p-c1',
    bracketId: 'bracket-c',
    name: 'Tố Vân Đào',
    sect: 'Võ Hồn Điện',
    martialSoul: 'Độc Lang',
    soulRank: 'Cấp 26 (Đại Hồn Sư)',
    soulLevel: 26,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=suwundao&backgroundColor=64748b',
    seedRank: 1,
    wins: 14,
    losses: 3,
    winRate: 82.4,
    bio: 'Chấp sự khai mở Hồn Lực cho Đường Tam tại Thánh Hồn Thôn.',
  },
  {
    id: 'p-c2',
    bracketId: 'bracket-c',
    name: 'Lão Kiệt Khắc',
    sect: 'Thánh Hồn Thôn',
    martialSoul: 'Cà Rốt Khí',
    soulRank: 'Cấp 15 (Hồn Sư)',
    soulLevel: 15,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=oldjack&backgroundColor=84cc16',
    seedRank: 2,
    wins: 11,
    losses: 4,
    winRate: 73.3,
    bio: 'Trưởng thôn khả kính luôn tự hào về lịch sử xuất hiện Hồn Thánh của làng.',
  },
  {
    id: 'p-c3',
    bracketId: 'bracket-c',
    name: 'Tiểu Tam (Ấu Niên)',
    sect: 'Thánh Hồn Thôn',
    martialSoul: 'Lam Ngân Thảo',
    soulRank: 'Cấp 29 (Đại Hồn Sư)',
    soulLevel: 29,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=youngtangsan&backgroundColor=0284c7',
    seedRank: 3,
    wins: 12,
    losses: 2,
    winRate: 85.7,
    bio: 'Thiên tài bẩm sinh Tiên Thiên Mãn Hồn Lực với Huyền Thiên Công.',
  },
  {
    id: 'p-c4',
    bracketId: 'bracket-c',
    name: 'Tiêu Trần Vũ',
    sect: 'Nặc Đinh',
    martialSoul: 'Lang Thú Hồn',
    soulRank: 'Cấp 21 (Đại Hồn Sư)',
    soulLevel: 21,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=xiaochenwu&backgroundColor=f59e0b',
    seedRank: 4,
    wins: 9,
    losses: 5,
    winRate: 64.3,
    bio: 'Thủ lĩnh học sinh quý tộc học viện Nặc Đinh.',
  },
  {
    id: 'p-c5',
    bracketId: 'bracket-c',
    name: 'Vương Thánh',
    sect: 'Nặc Đinh',
    martialSoul: 'Chiến Hổ',
    soulRank: 'Cấp 19 (Hồn Sư)',
    soulLevel: 19,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=wangsheng&backgroundColor=d97706',
    seedRank: 5,
    wins: 8,
    losses: 6,
    winRate: 57.1,
    bio: 'Đại ca phòng ký túc xá Thất Xá trước khi Đường Tam và Tiểu Vũ tới.',
  },
  {
    id: 'p-c6',
    bracketId: 'bracket-c',
    name: 'Liễu Long',
    sect: 'Nặc Đinh',
    martialSoul: 'Trường Côn',
    soulRank: 'Cấp 18 (Hồn Sư)',
    soulLevel: 18,
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=liulong&backgroundColor=475569',
    seedRank: 6,
    wins: 7,
    losses: 7,
    winRate: 50.0,
    bio: 'Tốc công côn pháp uyển chuyển linh hoạt.',
  },
];

export function getInitialTournamentData() {
  const participantsMap: Record<string, Participant> = {};
  [...BRACKET_A_PARTICIPANTS, ...BRACKET_B_PARTICIPANTS, ...BRACKET_C_PARTICIPANTS].forEach(p => {
    participantsMap[p.id] = p;
  });

  const matchesMap: Record<string, any> = {
    ...generateTournamentBracket('bracket-a', BRACKET_A_PARTICIPANTS),
    ...generateTournamentBracket('bracket-b', BRACKET_B_PARTICIPANTS),
    ...generateTournamentBracket('bracket-c', BRACKET_C_PARTICIPANTS),
  };

  return {
    brackets: DEFAULT_BRACKETS,
    participants: participantsMap,
    matches: matchesMap,
  };
}
